export const SK = {
  common: {
    loadingCookbook: 'Načítavam kuchárku...',
    loadingRecipe: 'Načítavam recept...',
    recipeNotFound: 'Recept sa nenašiel.',
    backHome: 'Späť domov',
    save: 'Uložiť recept',
    reset: 'Začať odznova',
    retry: 'Skúsiť znova',
  },
  home: {
    addFromPhoto: 'Pridať recept z fotky',
    addFromPhotoHint: 'Pusť obrázok sem alebo ťukni a vyber fotku.',
    emptyTitle: 'Tvoja kuchárka začína jednou fotkou.',
    emptySteps: [
      'Nahraj fotku receptu.',
      'Skontroluj a uprav ingrediencie a kroky.',
      'Ulož recept a var kedykoľvek.',
    ],
    cookAgain: 'Variť znova',
    latest: 'Najnovšie pridané',
    breakfast: 'Raňajkové recepty',
    savory: 'Slané jedlá',
    sweet: 'Sladké recepty',
  },
  add: {
    title: 'Pridať recept',
    modes: {
      photo: 'Fotka',
      url: 'URL',
      manual: 'Ručne',
    },
    uploadTitle: 'Nahraj fotku receptu',
    uploadHint: 'Odfotť recept alebo vyber obrázok z galérie.',
    urlLabel: 'Adresa receptu',
    urlPlaceholder: 'https://example.com/recept',
    urlButton: 'Importovať z URL',
    manualButton: 'Vytvoriť ručne',
    parsingImage: 'Spracovávam recept z fotky...',
    parsingUrl: 'Spracovávam recept z URL...',
    parsingHint: 'Toto je zatiaľ simulované AI spracovanie.',
    parseErrorTitle: 'Recept sa nepodarilo spracovať',
  },
  preview: {
    title: 'Skontroluj recept',
    recipeTitle: 'Názov',
    servings: 'Porcie',
    ingredients: 'Ingrediencie',
    ingredientName: 'Ingrediencia',
    amount: 'Množstvo',
    unit: 'Jednotka',
    optional: 'Voliteľné',
    addIngredient: '+ Pridať ingredienciu',
    steps: 'Postup',
    step: 'Krok',
    addStep: '+ Pridať krok',
  },
  detail: {
    recipe: 'Recept',
    flexibleTime: 'Bez času',
    easy: 'Jednoduché',
    startCooking: 'Začať variť',
    servings: 'Počet porcií',
    ingredients: 'Ingrediencie',
    steps: 'Postup',
    ingredientsCount: 'ingrediencií',
    stepsCount: 'krokov',
  },
  cookMode: {
    exit: 'Ukončiť',
    step: 'Krok',
    previous: 'Predchádzajúci',
    next: 'Ďalší',
  },
  tags: {
    breakfast: 'raňajky',
    quick: 'rýchle',
    starter: 'predjedlo',
    main: 'hlavné',
    side: 'príloha',
    sauce: 'omáčka',
    dessert: 'dezert',
    oat: 'ovsené',
    sweet: 'sladké',
  },
};
